# Generated by Django 3.0.8 on 2020-08-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200803_0745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='data_completed',
            new_name='date_completed',
        ),
    ]
